# Executor settings
executor: slurm
jobs: 100  # Maximum number of simultaneous jobs

# Default resources for all rules
default-resources:
        - runtime=60                  # Default 60 minutes
        - mem_mb=12000                 # Default 4GB RAM
        - cpus_per_task=8            # Default 1 CPU

# Retry failed jobs
retries: 2

slurm:
        status-check-interval: 10
        job-name: "{rule}.{wildcards.sample}"
        output: "logs/slurm/{rule}_{wildcards.sample}.out"
        error: "logs/slurm/{rule}_{wildcards.sample}.err"
latency-wait: 10

# Keep going if some jobs fail
keep-going: false
